package br.com.foursys.locadora.util;

public class Mensagem {

	public static String problemasNoLogin = "Problemas no login!";
	public static String credenciaisInvalidas = "Credenciais inválidas!";
	public static String sucesso = "Sucesso!";
	public static String filmeSalvo = "Filme salvo com sucesso!";
	public static String filmeAlterado = "Filme alterado com sucesso!";
	public static String clienteSalvo = "Cliente salvo com sucesso!";
	public static String funcionarioSalvo = "Funcionário salvo com sucesso!";
	public static String funcionarioAlterado = "Funcionário alterado com sucesso!";
	public static String clienteAlterado = "Cliente alterado com sucesso!";
	public static String locacaoSalva = "Locação salva com sucesso!";
	public static String devolucaoSalva = "Devolução salva com sucesso!";
	public static String campoObrigatorio = "Campo obrigatório!";
	public static String dadosInvalidos = "Dados inválidos!";
	public static String informeNome = "Informe o nome.";
	public static String informeGenero = "Informe o gênero.";
	public static String informeValor = "Informe o valor.";
	public static String informeDisponivel = "Informe se está disponível.";
	public static String informePromocao = "Informe se está em promoção.";
	public static String informeValorPromocao = "Informe o valor da promoção.";
	public static String informeCpf = "Informe o CPF.";
	public static String cpfInvalido = "CPF inválido.";
	public static String rgInvalido = "RG inválido.";
	public static String emailInvalido = "E-mail inválido.";
	public static String dataNascimentoInvalida = "Data de nascimento inválida.";
	public static String dataDevolucaoInvalida = "Data de devolução inválida.";
	public static String informeRg = "Informe o RG.";
	public static String informeDataNascimento = "Informe a data de nascimento.";
	public static String informeDataDevolucao = "Informe a data de devolução.";
	public static String informeIdade = "Informe a idade.";
	public static String informeSexo = "Informe o sexo.";
	public static String informeLogradouro = "Informe o logradouro.";
	public static String informeNumero = "Informe o número.";
	public static String informeBairro = "Informe o bairro.";
	public static String informeCep = "Informe o CEP.";
	public static String informeEstado = "Informe o estado.";
	public static String informeCidade = "Informe a cidade.";
	public static String informeLogin = "Informe o login.";
	public static String informeFuncionario = "Informe o funcionário.";
	public static String informeCliente = "Informe o cliente.";
	public static String informeFilme = "Informe pelo menos um filme.";
	public static String informeFormaPagamento = "Informe a forma de pagamento.";
	public static String informeSenha = "Informe a senha.";
	public static String erroSalvarFilme = "Erro ao salvar o filme!";
	public static String erroSalvarCliente = "Erro ao salvar o cliente!";
	public static String erroSalvarFuncionario = "Erro ao salvar o funcionário!";
	public static String erroSalvarLocacao = "Erro ao salvar a locação!";
	public static String erroSalvarDevolucao = "Erro ao salvar a devolução!";
	public static String erroAlterarFilme = "Erro ao alterar o filme!";
	public static String erroAlterarFuncionario = "Erro ao alterar o funcionário!";
	public static String erroExcluirFuncionario = "Não foi possível excluir o funcionário, pois existem locações atribuídas a este funcionário!";
	public static String erroExcluirFilme = "Não foi possível excluir o filme, pois existem locações atribuídas a este filme!";
	public static String erroExcluirCliente = "Não foi possível excluir o cleinte, pois existem locações atribuídas a este cliente!";
	public static String filmeExcluidoSucesso = "Filme excluido com sucesso.";
	public static String funcionarioExcluidoSucesso = "Funcionário excluido com sucesso.";
	public static String clienteExcluidoSucesso = "Cliente excluido com sucesso.";
	public static String erro = "Erro!";

}
